{
 "title": "Inlets Uplink dashboard",
 "time": { "from": "2023-01-24T16:13:30.790Z", "to": "2023-01-24T19:53:11.034Z" },
 "panels": [
  { "title": "Data Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP invocation rate",
   "type": "timeseries",
   "description": "Invocation rate per HTTP tunnel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (tunnel_name) (rate(dataplane_requests_total[$__rate_interval]))",
     "legendFormat": "{{tunnel_name}}"
    }
   ]
  },
  {
   "title": "Avarage HTTP request duration",
   "type": "timeseries",
   "description": "The average request duration per HTTP tunnel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (tunnel_name) (rate(dataplane_request_duration_seconds_sum [$__rate_interval])) / sum by (tunnel_name) (rate(dataplane_request_duration_seconds_count [$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dataplane_connections_gauge{type=\"tcp\"}",
     "legendFormat": "{{tunnel_name}}"
    }
   ]
  },
  {
   "title": "HTTP connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dataplane_connections_gauge{type=\"http\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP connection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(dataplane_connections_gauge{type=\"tcp\"}[$__rate_interval])",
     "legendFormat": "{{tunnel_name}}"
    }
   ]
  },
  {
   "title": "HTTP connection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "rate(dataplane_connections_gauge{type=\"http\"}[$__rate_interval])",
     "legendFormat": "{{tunnel_name}}"
    }
   ]
  },
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Connected clients",
   "type": "timeseries",
   "description": "Inlets clients connected to the control plane",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "controlplane_connected_gauge", "legendFormat": "{{tunnel_name}}" }
   ]
  },
  {
   "title": "Total clients",
   "type": "stat",
   "description": "Connected client across all tunnels",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(controlplane_connected_gauge)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control plane invocation rate",
   "type": "timeseries",
   "description": "Requests processed by connecting clients on the control plane.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(controlplane_requests_total[$__rate_interval])",
     "legendFormat": "{{tunnel_name}}: {{code}}"
    }
   ]
  }
 ]
}