apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: alexellis/inlets-pro:0.4
        imagePullPolicy: Always
        command: ["inlets-pro"]
        args:
        - "client"
        - "--connect=wss://EXIT_NODE_IP:8123/connect"
        - "--tcp-ports=80,443"
        - "--token=AUTHTOKENHERE"
        - "--license=LICENSE_JWT_HERE"

